version: "3.9"

services:
  translator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translator-agent
    ports:
      - "8200:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
